##2.Working with Numpy arrays 



##Aim:
To Work with numpy Arrays.
##CODE:
##EXAMPLE 1:
	Using 1-dimentional array
  Description:
  An array that has 0-D arrays as its elements is called uni-dimensional or       1-D   array.
	These are the most common and basic arrays.


  

---



In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5]) #creating np array
print(arr) #prints elements in array
print(type(arr)) #prints type of array



[1 2 3 4 5]
<class 'numpy.ndarray'>


##Output:
[1 2 3 4 5]
<class 'numpy.ndarray'>

##EXAMPLE 2 	
	Using 2-dimentional array

##Description:
An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]]) #creating np array
print(arr) #prints elements in array
print(type(arr)) #prints type of array



[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


##Output:
[[1 2 3]
 [4 5 6]] <br>
<class 'numpy.ndarray'>

##EXAMPLE 3
	Using 3-dimentional array
##Description:
  An array that has 2-D arrays (matrices) as its elements is called 3-D array,
	These are often used to represent a 3rd order tensor.
  ---


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


##Output:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

---

Reference: <br>
https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp